site_name: "Python - Módulo 7: Dicionários"

theme: readthedocs

nav:
    - index.md
    - 01_python-aula-39-o-que-e-um-dicionari.md
    - 02_python-aula-40-o-que-usar-dicionarios-o.md
    - 03_python-aula-41-como-acessar-um-elemento-de-um-dicionario-us.md
    - 04_python-aula-42-como-incluir-e-alterar-elementos-de-um-dicionari.md
    - 05_python-aula-43-como-localizar-elementos-em-um-dicionari.md
    - 06_python-aula-44-quantidade-de-elementos-de-um-di.md
    - 07_python-aula-45-como-acessar-chaves-valores-e-itens-em-um-di.md
    - 08_python-aula-46-como-ordenar-os-elementos-de-um-dicionari.md
    - 09_python-aula-47-como-excluir-elementos-de-um-dicionari.md
    - 10_python-aula-48-exercicio-sobre-dic.md
