site_name: "Python - Módulo 2: Operadores"

theme: readthedocs

nav:
    - index.md
    - 01_python-aula-08-operadores-aritmeticos-e.md
    - 02_python-aula-09-operadores-de-comparacao-e.md
    - 03_python-aula-10-operadores-de-atribuicao-e.md
    - 04_python-aula-11-operadores-logicos-e.md
